# -*- coding: utf-8 -*-
"""tic-tac-toeipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_VOjLtztq91RijAmjmLdBAwI9zXHt1D
"""

board = [['-', '-', '-'],
        ['-', '-', '-'],
        ['-', '-', '-']]


def check_mark (row, col):
  if board[row][col] == '-':
    return True
  return False
  
def place_mark(row, col, player):
  if player == 1:
    player_char = 'X'
  else:
    player_char = 'O'
  board[row][col] = player_char
  print(board)


def check_win (player):
  if player == 1:
    symbol = 'X'
  elif player == 2:
    symbol = 'O'

  looking_for = [symbol for i in range(3)]
  
  has_won = False
  for row in range(3):
    if looking_for == board[row]:
      as_won = True
    col = [board[i][row] for i in range(3)]
    if looking_for == col:
      has_won = True

    diag = [board[i][i] for i in range(3)]
    if looking_for == diag:
      has_won = True
    diag = [board[0][2], board[1][1], board[2][0]]
    if looking_for == diag:
      has_won = True

    return has_won

def main(row, col, player):
  print('player 1, enter your desired coordinates: ')
  row = int(input('enter row number 0-2: '))
  col = int(input('enter column number 0-2: '))

  while check_mark(row, col) == True:
    print('Player 2 enter your coordinates.')
    row = int(input('enter row number 0-2: '))
    col = int(input('enter column number 0-2: '))
    board.append(row)
    board.append(col)
    print(board)

    print('player 1, enter your desired coordinates: ')
    row = int(input('enter row number 0-2: '))
    col = int(input('enter column number 0-2: '))
    board.append(row)
    board.append(col)
    print(board)
  else:
    print('invalid selection. Enter valid coordinates.')

  place_mark(row, col, player)

  if check_win(player) == True:
    print('Congrats player 1 has won!')
    gameIsPlaying = False
  else:
    print('you lose')


main(row, col, player)

