# -*- coding: utf-8 -*-
"""tic_tac_toe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x_VOjLtztq91RijAmjmLdBAwI9zXHt1D
"""

board = [['-', '-', '-'],
        ['-', '-', '-'],
        ['-', '-', '-']]
def print_board(board):
  for row in board:
    print(row)

def check_mark(row,column):
  if board[row][column] == '-':
    print('True')
  else:
    print('False')
  return board[row][column]

def place_mark(row,column,player_id):
  if player_id == 1:
    board[row][column] == 'X'
  else:
    if player_id == 2:
      board[row][column] == 'O'
  return board[row][column]

  for i in range(3):
    possible.append(board[i][0] + board[i][1] + board[i][2])
  for i in range(3):
    possible.append(board[0][i] + board[1][i] + board[2][i])
  return possible.append
      
print(place_mark)

def check_win(player_id):
  win = True
  for row in range(len(board)):
    for col in range(len(board)):
      if board[row][column] == decorator:
        win = True
      else:
        win = False

print('testing print_board')
print(print_board(board))

print(check_mark(1,2))
print('hello', place_mark(1,2,2))
print(print_board(board))